version: "3"
services:

  selenium-hub:
    image: selenium/hub
    ports:
      - "5000:5000"
    environment:
        GRID_MAX_SESSION: 16
        GRID_BROWSER_TIMEOUT: 300
        GRID_TIMEOUT: 300

  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 5000
      NODE_MAX_SESSION: 2
      NODE_MAX_INSTANCES: 2
      
