"""empty message

Revision ID: 46493a0aa5f6
Revises: 
Create Date: 2023-06-18 22:11:50.356887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46493a0aa5f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=160), nullable=False),
    sa.Column('id_imdb', sa.String(length=7), nullable=False),
    sa.Column('atores', sa.String(length=1000), nullable=False),
    sa.Column('diretor', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_imdb'),
    sa.UniqueConstraint('titulo')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('funcao', sa.String(length=50), server_default='user', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('corpo', sa.String(length=500), nullable=True),
    sa.Column('estrelas', sa.Integer(), nullable=False),
    sa.Column('id_filme', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_filme'], ['filme.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaliacao')
    op.drop_table('usuario')
    op.drop_table('filme')
    # ### end Alembic commands ###
