"""empty message

Revision ID: be3480a880f9
Revises: 271b7da8d8fc
Create Date: 2022-01-08 22:47:20.571169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be3480a880f9'
down_revision = '271b7da8d8fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=160), nullable=False),
    sa.Column('id_imdb', sa.String(length=7), nullable=False),
    sa.Column('atores', sa.String(length=1000), nullable=False),
    sa.Column('diretor', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_imdb'),
    sa.UniqueConstraint('titulo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filme')
    # ### end Alembic commands ###
