"""empty message

Revision ID: edafeb7469ef
Revises: be3480a880f9
Create Date: 2022-01-09 03:02:16.281332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edafeb7469ef'
down_revision = 'be3480a880f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('corpo', sa.String(length=500), nullable=True),
    sa.Column('estrelas', sa.Integer(), nullable=False),
    sa.Column('id_filme', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_filme'], ['filme.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaliacao')
    # ### end Alembic commands ###
