name: Testes

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-latest
          - windows-latest

    steps:

      - uses: actions/checkout@v2  
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.10

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt
          pip install pyleniumio

      - name: Executando testes unitários
        run: pytest --disable-warnings tests/unit
        
      - uses: browser-actions/setup-chrome@v1
        
      - name: Configurando chrome driver para Windows
        if: matrix.os == 'windows-latest'
        run: chromedriver --url-base=/wd/hub
          
      - name: Configurando chrome driver para Mac
        if: matrix.os == 'macos-latest'
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
          
      - name: Configurando chrome driver para Linux
        if: matrix.os == 'ubuntu-20.04'
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
        
      
      - name: Executando sistema
        run: python app.py &
          
      - name: Wait for application to start
        run: sleep 10
      
      - name: Executando testes de sistema
        run: pytest --disable-warnings tests/e2e
        
