name: Testes

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-11
          - windows-2019

    steps:

      - uses: actions/checkout@v2  
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.10

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt
          pip install pyleniumio

      - name: Executando testes unitários
        run: pytest --disable-warnings tests/unit

      - name: Executando testes de sistema
        run: |
          python app.py
          pytest --disable-warnings tests/e2e
        
      - name: 'setup-chromedriver'
      - uses: nanasess/setup-chromedriver@v2
        - run: |
          {% if matrix.os == 'windows-2019' %}
          chromedriver --url-base=/wd/hub
          {% else %}
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
          {% endif %}

      
      - name: Executando testes de sistema
        run: |
          python app.py
          pytest --disable-warnings tests/e2e
