name: Testes

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - name: Configurar ambiente Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.15

      - name: Verificar versão do Python
        run: python --version

      - name: Configurar ambiente do sistema
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y python3-dev python3-pip

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar testes
        run: pytest
